<?php
header("Access-Control-Allow-Origin: http://localhost");
header("Access-Control-Allow-Credentials: true");
header("Content-Type: text/plain");

http_response_code(404);
echo "Disabled. Password hashes are generated by setup.php and register.php.";
?>
